import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Koh Sdach 79 Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="overflow-y-auto" lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} transition-colors duration-300 bg-background text-foreground`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
